/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.sequences


import io.github.novemdecillion.DefaultSchema

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>event_id_seq</code>
 */
val EVENT_ID_SEQ: Sequence<Long> = Internal.createSequence("event_id_seq", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT.nullable(false), null, null, null, null, true, null)
