/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.keys


import io.github.novemdecillion.tables.EventTable
import io.github.novemdecillion.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.tables.SnapshotTable
import io.github.novemdecillion.tables.records.EventRecord
import io.github.novemdecillion.tables.records.FlywaySchemaHistoryRecord
import io.github.novemdecillion.tables.records.SnapshotRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val EVENT_PKEY: UniqueKey<EventRecord> = Internal.createUniqueKey(EventTable.EVENT, DSL.name("event_pkey"), arrayOf(EventTable.EVENT.EVENT_ID), true)
val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val SNAPSHOT_PKEY: UniqueKey<SnapshotRecord> = Internal.createUniqueKey(SnapshotTable.SNAPSHOT, DSL.name("snapshot_pkey"), arrayOf(SnapshotTable.SNAPSHOT.AGGREGATE_ID), true)
