/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.tables.references


import io.github.novemdecillion.tables.EventTable
import io.github.novemdecillion.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.tables.SnapshotTable



/**
 * The table <code>event</code>.
 */
val EVENT = EventTable.EVENT

/**
 * The table <code>flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>snapshot</code>.
 */
val SNAPSHOT = SnapshotTable.SNAPSHOT
