/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.tables


import io.github.novemdecillion.DefaultSchema
import io.github.novemdecillion.keys.SNAPSHOT_PKEY
import io.github.novemdecillion.tables.records.SnapshotRecord

import java.util.UUID

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SnapshotTable(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SnapshotRecord>?,
    aliased: Table<SnapshotRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SnapshotRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>snapshot</code>
         */
        val SNAPSHOT = SnapshotTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SnapshotRecord> = SnapshotRecord::class.java

    /**
     * The column <code>snapshot.aggregate_id</code>.
     */
    val AGGREGATE_ID: TableField<SnapshotRecord, UUID?> = createField(DSL.name("aggregate_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>snapshot.event_id</code>.
     */
    val EVENT_ID: TableField<SnapshotRecord, Long?> = createField(DSL.name("event_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>snapshot.payload</code>.
     */
    val PAYLOAD: TableField<SnapshotRecord, JSONB?> = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SnapshotRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SnapshotRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>snapshot</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>snapshot</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>snapshot</code> table reference
     */
    constructor(): this(DSL.name("snapshot"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SnapshotRecord>): this(Internal.createPathAlias(child, key), child, key, SNAPSHOT, null)
    override fun getSchema(): Schema = DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<SnapshotRecord> = SNAPSHOT_PKEY
    override fun getKeys(): List<UniqueKey<SnapshotRecord>> = listOf(SNAPSHOT_PKEY)
    override fun `as`(alias: String): SnapshotTable = SnapshotTable(DSL.name(alias), this)
    override fun `as`(alias: Name): SnapshotTable = SnapshotTable(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SnapshotTable = SnapshotTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SnapshotTable = SnapshotTable(name, null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<UUID?, Long?, JSONB?> = super.fieldsRow() as Row3<UUID?, Long?, JSONB?>
}
