/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.tables.pojos


import io.github.novemdecillion.tables.interfaces.IEvent

import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class EventEntity(
    override var eventId: Long? = null, 
    override var aggregateId: UUID? = null, 
    override var commandName: String? = null, 
    override var payload: JSONB? = null, 
    override var saveAt: OffsetDateTime? = null
): IEvent {


    override fun toString(): String {
        val sb = StringBuilder("EventEntity (")

        sb.append(eventId)
        sb.append(", ").append(aggregateId)
        sb.append(", ").append(commandName)
        sb.append(", ").append(payload)
        sb.append(", ").append(saveAt)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: IEvent) {
        eventId = from.eventId
        aggregateId = from.aggregateId
        commandName = from.commandName
        payload = from.payload
        saveAt = from.saveAt
    }

    override fun <E : IEvent> into(into: E): E {
        into.from(this)
        return into
    }
}
