/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.tables.pojos


import io.github.novemdecillion.tables.interfaces.ISnapshot

import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SnapshotEntity(
    override var aggregateId: UUID? = null, 
    override var eventId: Long? = null, 
    override var payload: JSONB? = null
): ISnapshot {


    override fun toString(): String {
        val sb = StringBuilder("SnapshotEntity (")

        sb.append(aggregateId)
        sb.append(", ").append(eventId)
        sb.append(", ").append(payload)

        sb.append(")")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    override fun from(from: ISnapshot) {
        aggregateId = from.aggregateId
        eventId = from.eventId
        payload = from.payload
    }

    override fun <E : ISnapshot> into(into: E): E {
        into.from(this)
        return into
    }
}
