/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion


import io.github.novemdecillion.sequences.EVENT_ID_SEQ
import io.github.novemdecillion.tables.EventTable
import io.github.novemdecillion.tables.FlywaySchemaHistoryTable
import io.github.novemdecillion.tables.SnapshotTable

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA = DefaultSchema()
    }

    /**
     * The table <code>event</code>.
     */
    val EVENT get() = EventTable.EVENT

    /**
     * The table <code>flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY get() = FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>snapshot</code>.
     */
    val SNAPSHOT get() = SnapshotTable.SNAPSHOT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        EVENT_ID_SEQ
    )

    override fun getTables(): List<Table<*>> = listOf(
        EventTable.EVENT,
        FlywaySchemaHistoryTable.FLYWAY_SCHEMA_HISTORY,
        SnapshotTable.SNAPSHOT
    )
}
