/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.tables.interfaces


import java.io.Serializable
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IEvent : Serializable {
    var eventId: Long?
    var aggregateId: UUID?
    var commandName: String?
    var payload: JSONB?
    var saveAt: OffsetDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IEvent
     */
    fun from(from: IEvent)

    /**
     * Copy data into another generated Record/POJO implementing the common interface IEvent
     */
    fun <E : IEvent> into(into: E): E
}
