/*
 * This file is generated by jOOQ.
 */
package io.github.novemdecillion.tables.interfaces


import java.io.Serializable
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ISnapshot : Serializable {
    var aggregateId: UUID?
    var eventId: Long?
    var payload: JSONB?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISnapshot
     */
    fun from(from: ISnapshot)

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISnapshot
     */
    fun <E : ISnapshot> into(into: E): E
}
